Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -208,27 +208,27 @@ jobs:
     steps:
     - checkout
       # Checkout code from git
-      - run:
-          name: Run migrations
-          command: |
-            # Your code here
-            cd backend
-            npm install
-            npm run migrations > migrations_dump.txt
-            #exit 1
-      - run:
-          name: Send migration results to memstash
-          command: |
-            # Your code here
-          name: Send migration results to kvdb.io
-          command: |
-            if grep -q "has been executed successfully." ./backend/migrations_dump.txt
-            then
-              echo "Invoking KVDB"
-              curl https://kvdb.io/${KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
-            fi
-            #exit 1
-    # Here's where you will add some code to rollback on failure      
+    - run:
+        name: Run migrations
+        command: |
+          # Your code here
+          cd backend
+          npm install
+          npm run migrations > migrations_dump.txt
+          #exit 1
+    - run:
+        name: Send migration results to memstash
+        command: |
+          # Your code here
+        name: Send migration results to kvdb.io
+        command: |
+          if grep -q "has been executed successfully." ./backend/migrations_dump.txt
+          then
+            echo "Invoking KVDB"
+            curl https://kvdb.io/${KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
+          fi
+          #exit 1
+  # Here's where you will add some code to rollback on failure      
 
   deploy-frontend:
     docker:
